wallpaper {
    monitor = HDMI-A-1
    path = /home/hasakev/.config/hypr/wallpapers/chongqing-blue.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/hasakev/.config/hypr/wallpapers/chongqing-blue.png
    fit_mode = cover
}

# Moonlight/Sunshine virtual output (created by sunshine-headless.service).
# Without this, remote sessions get a blank background.
wallpaper {
    monitor = HEADLESS-SUNSHINE
    path = /home/hasakev/.config/hypr/wallpapers/chongqing-blue.png
    fit_mode = cover
}

splash = false
